//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GospelInnMinistry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int Id { get; set; }
        public string MediaName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ContentLocation { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<bool> isVedio { get; set; }
        public string VedioPreacher { get; set; }
        public string VedioDesciption { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
    }
}
