//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GospelInnMinistry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> userId { get; set; }
        public string PhoneNumber { get; set; }
        public string Message1 { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    
        public virtual User User { get; set; }
    }
}
