//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GospelInnMinistry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long id { get; set; }
        public string newsTitle { get; set; }
        public string mesaage { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string author { get; set; }
        public string imageLocation { get; set; }
    }
}
